apiVersion: v1
kind: Template
metadata:
  name: controlpanel-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp    
    generation: 1
    labels:
      app: controlpanelservice
    name: controlpanelservice
  spec:
    replicas: ${REPLICAS}
    selector:
      app: controlpanelservice
      deploymentconfig: controlpanelservice
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp        
        labels:
          app: controlpanelservice
          deploymentconfig: controlpanelservice
      spec:
        containers:
        - env:
          - name: SERVER_NAME
            value: ${SERVER_NAME}
          - name: KAFKAENABLED
            value: ${KAFKAENABLED}
          - name: REALTIMEDBUSEAUTH
            value: ${REALTIMEDBUSEAUTH}                        
          image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/controlpanel:${MODULE_TAG}
          imagePullPolicy: Always
          name: controlpanelservice
          ports:
          - containerPort: 18000
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 3Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp
              name: controlpanelservice-volume-1
            - mountPath: /usr/local/webprojects
              name: webprojects-volume              
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - emptyDir: {}
            name: controlpanelservice-volume-1
          - name: webprojects-volume
            persistentVolumeClaim:
              claimName: pvc-webprojects             
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - controlpanelservice
        from:
          kind: ImageStreamTag
          name: controlpanel:${MODULE_TAG}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: controlpanelservice
    name: controlpanelservice
  spec:
    ports:
    - name: 18000-tcp
      port: 18000
      protocol: TCP
      targetPort: 18000
    selector:
      app: controlpanelservice
      deploymentconfig: controlpanelservice
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}  
parameters:    
- name: MODULE_TAG 
  description: Docker image tag     
  required: true 
- name: PROJECT 
  description: Project name    
  required: true  
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true   
- name: SERVER_NAME 
  description: Load Balancer dns name    
  required: true 
- name: KAFKAENABLED 
  description: Kafka broker enable flag    
  required: true    
- name: REALTIMEDBUSEAUTH
  description: Enable MongoDb authentication    
  required: false         
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"       
