apiVersion: v1
kind: Template
metadata:
  name: iotbroker-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp    
    generation: 1
    labels:
      app: iotbrokerservice
    name: iotbrokerservice
  spec:
    replicas: ${REPLICAS}
    selector:
      app: iotbrokerservice
      deploymentconfig: iotbrokerservice
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp        
        labels:
          app: iotbrokerservice
          deploymentconfig: iotbrokerservice
      spec:
        containers:
        - env:
          - name: SERVER_NAME
            value: ${SERVER_NAME}
          - name: KAFKAENABLED
            value: ${KAFKAENABLED}  
          - name: REALTIMEDBUSEAUTH
            value: ${REALTIMEDBUSEAUTH}                      
          image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/iotbroker:${MODULE_TAG}
          imagePullPolicy: Always
          name: iotbrokerservice
          ports:
          - containerPort: 1883
            protocol: TCP
          - containerPort: 19000
            protocol: TCP
          - containerPort: 8883
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 3Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: iotbrokerservice-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: iotbrokerservice-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - iotbrokerservice
        from:
          kind: ImageStreamTag
          name: iotbroker:${MODULE_TAG}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: iotbrokerservice
    name: iotbrokerservice
  spec:
    ports:
    - name: 1883-tcp
      port: 1883
      protocol: TCP
      targetPort: 1883
    - name: 8883-tcp
      port: 8883
      protocol: TCP
      targetPort: 8883
    - name: 19000-tcp
      port: 19000
      protocol: TCP
      targetPort: 19000
    selector:
      app: iotbrokerservice
      deploymentconfig: iotbrokerservice
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}  
parameters:    
- name: MODULE_TAG 
  description: Docker image tag     
  required: true 
- name: PROJECT 
  description: Project name    
  required: true  
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true   
- name: SERVER_NAME 
  description: Load Balancer dns name    
  required: true 
- name: KAFKAENABLED 
  description: Kafka broker enable flag    
  required: true   
- name: REALTIMEDBUSEAUTH
  description: Enable MongoDb authentication    
  required: false            
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"      
