apiVersion: v1
kind: Template
metadata:
  name: devicesimulator-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp    
    generation: 1
    labels:
      app: devicesimulator
    name: devicesimulator
  spec:
    replicas: ${REPLICAS}
    selector:
      app: devicesimulator
      deploymentconfig: devicesimulator
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp        
        labels:
          app: devicesimulator
          deploymentconfig: devicesimulator
      spec:
        containers:
        - env:
          - name: SERVER_NAME
            value: ${SERVER_NAME}
          - name: REALTIMEDBUSEAUTH
            value: ${REALTIMEDBUSEAUTH}            
          image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/devicesimulator:${MODULE_TAG}
          imagePullPolicy: Always
          name: devicesimulator
          ports:
          - containerPort: 19200
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 3Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: devicesimulator-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: devicesimulator-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - devicesimulator
        from:
          kind: ImageStreamTag
          name: devicesimulator:${MODULE_TAG}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: devicesimulator
    name: devicesimulator
  spec:
    ports:
    - name: 19200-tcp
      port: 19200
      protocol: TCP
      targetPort: 19200
    selector:
      app: devicesimulator
      deploymentconfig: devicesimulator
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}    
parameters:    
- name: MODULE_TAG 
  description: Docker image tag     
  required: true 
- name: PROJECT 
  description: Project name    
  required: true
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true    
- name: SERVER_NAME 
  description: Load Balancer dns name    
  required: true    
- name: REALTIMEDBUSEAUTH
  description: Enable MongoDb authentication    
  required: false        
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"       