apiVersion: v1
kind: Template
metadata:
  name: loadbalancer-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp   
    generation: 1
    labels:
      app: loadbalancerservice
    name: loadbalancerservice
  spec:
    replicas: ${REPLICAS}
    selector:
      app: loadbalancerservice
      deploymentconfig: loadbalancerservice
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp       
        labels:
          app: loadbalancerservice
          deploymentconfig: loadbalancerservice
      spec:
        containers:
        - env:
          - name: SERVER_NAME
            value: ${SERVER_NAME}
          image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/nginx:${INFRA_TAG}
          imagePullPolicy: Always
          name: loadbalancerservice
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/local/webprojects
              name: webprojects-volume        
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: webprojects-volume
            persistentVolumeClaim:
              claimName: pvc-webprojects         
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - loadbalancerservice
        from:
          kind: ImageStreamTag
          name: nginx:${INFRA_TAG}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: loadbalancerservice
    name: loadbalancerservice
  spec:
    ports:
    - name: 443-tcp
      port: 443
      protocol: TCP
      targetPort: 443
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: loadbalancerservice
      deploymentconfig: loadbalancerservice
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}    
parameters:    
- name: INFRA_TAG 
  description: Docker image tag     
  required: true 
- name: PROJECT 
  description: Project name    
  required: true  
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true  
- name: SERVER_NAME 
  description: Load Balancer dns name    
  required: true        
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"     