apiVersion: v1
kind: Template
metadata:
  name: router-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp    
    generation: 1
    labels:
      app: routerservice
    name: routerservice
  spec:
    replicas: ${REPLICAS}
    selector:
      app: routerservice
      deploymentconfig: routerservice
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          app: routerservice
          deploymentconfig: routerservice
      spec:
        containers:
        - env:
          - name: SERVER_NAME
            value: ${SERVER_NAME}
          - name: REALTIMEDBUSEAUTH
            value: ${REALTIMEDBUSEAUTH}            
          image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/router:${MODULE_TAG}
          imagePullPolicy: Always
          name: routerservice
          ports:
          - containerPort: 20000
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 3Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: routerservice-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: routerservice-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - routerservice
        from:
          kind: ImageStreamTag
          name: router:${MODULE_TAG}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: routerservice
    name: routerservice
  spec:
    ports:
    - name: 20000-tcp
      port: 20000
      protocol: TCP
      targetPort: 20000
    selector:
      app: routerservice
      deploymentconfig: routerservice
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}   
parameters:    
- name: MODULE_TAG 
  description: Docker image tag     
  required: true 
- name: PROJECT 
  description: Project name    
  required: true
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true     
- name: SERVER_NAME 
  description: Load Balancer dns name    
  required: true  
- name: REALTIMEDBUSEAUTH
  description: Enable MongoDb authentication    
  required: false          
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"     