apiVersion: v1
kind: Template
metadata:
  name: configinit-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: configinit
    name: configinit
  spec:
    replicas: ${REPLICAS}
    selector:
      app: configinit
      deploymentconfig: configinit
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          app: configinit
          deploymentconfig: configinit
      spec:
        containers:
        - env:
          - name: REALTIMEDBUSEAUTH
            value: ${REALTIMEDBUSEAUTH}         
          image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/configinit:${MODULE_TAG}
          imagePullPolicy: Always
          name: configinit
          ports:
          - containerPort: 21000
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumes:
          - emptyDir: {}
            name: configinit-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - configinit
        from:
          kind: ImageStreamTag
          name: configinit:${MODULE_TAG}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: configinit
    name: configinit
  spec:
    ports:
    - name: 21000-tcp
      port: 21000
      protocol: TCP
      targetPort: 21000
    selector:
      app: configinit
      deploymentconfig: configinit
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- name: MODULE_TAG 
  description: Docker image tag     
  required: true 
- name: PROJECT 
  description: Project name    
  required: true 
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true  
- name: REALTIMEDBUSEAUTH
  description: Enable MongoDb authentication    
  required: false        
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"