apiVersion: v1
kind: Template
metadata:
  name: notebook-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: zeppelin
    name: zeppelin
  spec:
    replicas: ${REPLICAS}
    selector:
      app: zeppelin
      deploymentconfig: zeppelin
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          app: zeppelin
          deploymentconfig: zeppelin
      spec:
        containers:
        - env:
          - name: ZEPPELIN_PORT
            value: "8080"
          image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/notebook:latest
          imagePullPolicy: Always
          name: zeppelin
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 3Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - zeppelin
        from:
          kind: ImageStreamTag
          name: notebook:latest
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
parameters:    
- name: MODULE_TAG 
  description: Docker image tag     
  required: true 
- name: PROJECT 
  description: Project name    
  required: true
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true     
- name: SERVER_NAME 
  description: Load Balancer dns name    
  required: true 
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"     