apiVersion: v1
kind: Template
metadata:
  name: configdb-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: configdb
    name: configdb
  spec:
    replicas: ${REPLICAS}
    selector:
      app: configdb
      deploymentconfig: configdb
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          app: configdb
          deploymentconfig: configdb
      spec:
        containers:
        - image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/configdb:${PERSISTENCE_TAG}
          imagePullPolicy: Always
          name: configdb
          ports:
          - containerPort: 3306
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: configdb-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: configdb-volume
            persistentVolumeClaim:
              claimName: pvc-configdb        
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - configdb
        from:
          kind: ImageStreamTag
          name: configdb:${PERSISTENCE_TAG}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: configdb
    name: configdb
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: configdb
      deploymentconfig: configdb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- name: PERSISTENCE_TAG 
  description: Docker image tag     
  required: true 
- name: PROJECT 
  description: Project name    
  required: true 
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true       
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"         