apiVersion: v1
kind: Template
metadata: 
  name: schedulerdb-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: schedulerdb
    name: schedulerdb
  spec:
    replicas: ${REPLICAS}
    selector:
      app: schedulerdb
      deploymentconfig: schedulerdb
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          app: schedulerdb
          deploymentconfig: schedulerdb
      spec:
        containers:
        - image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/schedulerdb:${PERSISTENCE_TAG}
          imagePullPolicy: Always
          name: schedulerdb
          ports:
          - containerPort: 3306
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumes:
          - emptyDir: {}
            name: schedulerdb-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - schedulerdb
        from:
          kind: ImageStreamTag
          name: schedulerdb:${PERSISTENCE_TAG}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: schedulerdb
    name: schedulerdb
  spec:
    ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: schedulerdb
      deploymentconfig: schedulerdb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}    
parameters:
- name: PERSISTENCE_TAG 
  description: Docker image tag    
  required: true 
- name: PROJECT 
  description: Project name    
  required: true
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true        
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"    