apiVersion: v1
kind: Template
metadata: 
  name: realtimedb-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: realtimedb
    name: realtimedb
  spec:
    replicas: ${REPLICAS}
    selector:
      app: realtimedb
      deploymentconfig: realtimedb
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp     
        labels:
          app: realtimedb
          deploymentconfig: realtimedb
      spec:
        containers:
        - image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/realtimedb:${PERSISTENCE_TAG_MONGODB}
          imagePullPolicy: Always
          name: realtimedb
          ports:
          - containerPort: 27017
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/configdb
              name: realtimedb-volume-1
            - mountPath: /data/db
              name: realtimedb-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - emptyDir: {}
            name: realtimedb-volume-1
          - name: realtimedb-volume
            persistentVolumeClaim:
              claimName: pvc-realtimedb       
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - realtimedb
        from:
          kind: ImageStreamTag
          name: realtimedb:${PERSISTENCE_TAG_MONGODB}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: realtimedb
    name: realtimedb
  spec:
    ports:
    - name: 27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: realtimedb
      deploymentconfig: realtimedb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}    
parameters:
- name: PERSISTENCE_TAG_MONGODB 
  description: Docker image tag    
  required: true 
- name: PROJECT 
  description: Project name    
  required: true 
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true       
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"     