apiVersion: v1
kind: Template
metadata: 
  name: elasticdb-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp    
    generation: 1
    labels:
      app: elasticdb
    name: elasticdb
  spec:
    replicas: ${REPLICAS}
    selector:
      app: elasticdb
      deploymentconfig: elasticdb
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp        
        labels:
          app: elasticdb
          deploymentconfig: elasticdb
      spec:
        containers:
        - image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/elasticdb:${PERSISTENCE_TAG}
          imagePullPolicy: Always
          name: elasticdb
          ports:
          - containerPort: 9200
            protocol: TCP
          - containerPort: 9300
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumes:
          - emptyDir: {}
            name: elastic-volume
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - elasticdb
        from:
          kind: ImageStreamTag
          name: elasticdb:${PERSISTENCE_TAG}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: elasticdb
    name: elasticdb
  spec:
    ports:
    - name: 9200-tcp
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: 9300-tcp
      port: 9300
      protocol: TCP
      targetPort: 9300
    selector:
      app: elasticdb
      deploymentconfig: elasticdb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}  
parameters:
- name: PERSISTENCE_TAG 
  description: Docker image tag 
  required: true 
- name: PROJECT 
  description: Project name    
  required: true    
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true     
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"       