apiVersion: v1
kind: Template
metadata: 
  name: zookeeper-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    generation: 1
    labels:
      app: zookeeper
    name: zookeeper
  spec:
    replicas: ${REPLICAS}
    selector:
      app: zookeeper
      deploymentconfig: zookeeper
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        labels:
          app: zookeeper
          deploymentconfig: zookeeper
      spec:
        containers:
        - env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2182"
          image: docker-registry.default.svc:5000/${IMAGENAMESPACE}/zookeeper-secured:${PERSISTENCE_TAG}
          imagePullPolicy: Always
          name: zookeeper
          ports:
          - containerPort: 2181
            protocol: TCP
          - containerPort: 2888
            protocol: TCP
          - containerPort: 3888
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/zookeeper/log
            name: zookeeper-volume-1
          - mountPath: /etc/zookeeper/secrets
            name: zookeeper-volume-2
          - mountPath: /var/lib/zookeeper/data
            name: zookeeper-volume-3
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: zookeeper-volume-1
        - emptyDir: {}
          name: zookeeper-volume-2
        - emptyDir: {}
          name: zookeeper-volume-3
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - zookeeper
        from:
          kind: ImageStreamTag
          name: zookeeper-secured:${PERSISTENCE_TAG}
          namespace: ${IMAGENAMESPACE}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    labels:
      app: zookeeper
    name: zookeeper
  spec:
    ports:
    - name: 2181-tcp
      port: 2181
      protocol: TCP
      targetPort: 2181
    - name: 2888-tcp
      port: 2888
      protocol: TCP
      targetPort: 2888
    - name: 3888-tcp
      port: 3888
      protocol: TCP
      targetPort: 3888
    selector:
      app: zookeeper
      deploymentconfig: zookeeper
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
- name: PERSISTENCE_TAG 
  description: Docker image tag 
  required: true 
- name: PROJECT 
  description: Project name    
  required: true    
- name: IMAGENAMESPACE 
  description: Image name space    
  required: true     
- name: REPLICAS 
  description: Number of pods for this service   
  required: false
  value: "1"     