FROM mongo:3.4

# Metadata
LABEL module.maintainer="onesaitplatform@indra.es" \
	  module.name="realtimedb"	

# MongoDB environment
ENV MONGO_INITDB_DATABASE=onesaitplatform_rtdb 		

RUN chmod -R 777 /data/db

EXPOSE 27017

USER mongodb